### ISSUE TITLE
Building DXVK with this toolchain

### ISSUE THREAD

**Issue by SR-dude** [Zeckmathederg/mingw-w64-binary-builds#2]
This tool chain will compile wine correctly. That being said, building dxvk failed.
DXVK asked for --enable-threads=posix during compilation. I thought that was
enabled already.  It is. 

x86_64-w64-mingw32-g++  -o src/dxgi/dxgi.dll ....
/usr/x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libpthread.a(libwinpthread_la-thread.o): in function `pthread_create_wrapper':
/xxx/src/mingw-w64-v12.0.0/build-x86_64-winpthreads/../mingw-w64-libraries/winpthreads/src/thread.c:1544:(.text+0xad8): undefined reference to `_setjmp'

**Comment by zeckma-tech** [comment]
Looks like you have built MinGW-w64-12.0.0. This build was meant for 11.0.0 / 11.0.1. I haven't tested with 12.0.0, and it could be the root of the issue. Eventually, this repo will be obsolete as Rahul Chandra is working on doing static builds of GCC MinGW-w64 in GLFS, which could make the MinGW-w64 version irrelevant to some degree. 

I recommend building MinGW-w64 v11.0.1 and see if that helps.

If you wanna try the static GCC route, check: https://github.com/rahulc07/cross-sh-mingw and look through the shell scripts.

**Comment by SR-dude** [comment]
You're right. I scrapped the tool chain and built a new one with crosstool-ng. Posix threading is enabled by default with that suite. I just need to select  gcc 13 & mingW 11.  When it was done, it put build logs in the folder. I could snag the configure lines to see just what it is doing. There is no reason to think your GLFS instructions are not sound. And, I'll keep trying.

**Comment by SR-dude** [comment]
Off Topic
I posted a support ticket on the BLFS mailing list. It concerns steam not being able to connect because of some missing ssl certificate.  There I posted some logs.  My problem is I'm catching up, since I don't really know what ssl is about. In the past, I just copied from an ubuntu install to /usr/share/ca-certificate and that worked. BLFS puts nothing there.

**Comment by zeckma-tech** [comment]
> You're right. I scrapped the tool chain and built a new one with crosstool-ng. Posix threading is enabled by default with that suite. I just need to select gcc 13 & mingW 11. When it was done, it put build logs in the folder. I could snag the configure lines to see just what it is doing. There is no reason to think your GLFS instructions are not sound. And, I'll keep trying.

Trusting commands written by some random person is always sketchy and sometimes commands just don't work! LFS and BLFS sometimes have issues too! GLFS had issues in the past as well and will continue to. And nice to hear.

>  Off Topic
> I posted a support ticket on the BLFS mailing list. It concerns steam not being able to connect because of some missing ssl certificate. There I posted some logs. My problem is I'm catching up, since I don't really know what ssl is about. In the past, I just copied from an ubuntu install to /usr/share/ca-certificate and that worked. BLFS puts nothing there.

Yeah those sorta issues should be sent to GLFS instead as the BLFS editors don't wanna support Steam (you should have seen an email from me on the mailing list come your way which goes more in-depth with it).

Either way lemme know if the build works, then I'll close the issue. Or you can if you wish. You should have that power, too!

**Comment by SR-dude** [comment]
I'll mark this as solved for now.  But, I need some further testing with mingw. 

I saw your reply on the blfs mailing list.  I''l have to see just how your 'make-ca' instructions differ from blfs. Thanks for the tip.
